[env:max_freq]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
build_src_filter = +<max_freq.cpp> -<main.cpp> -<bonus.cpp>


[env:main]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp> -<max_freq.cpp> -<bonus.cpp>

lib_deps = 
    kosme/arduinoFFT @ ^2.0.4
    knolleary/PubSubClient @ ^2.8.0
    adafruit/Adafruit INA219 @ ^1.2.3
    jgromes/RadioLib @ ^6.6.0

[env:bonus]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
build_src_filter = +<bonus.cpp> -<main.cpp> -<max_freq.cpp>
lib_deps = 
	kosme/arduinoFFT @ ^2.0.4